#!/bin/bash

set -e

abort() {
    >&2 echo "$@"
    exit 1
}

iso_repack() {
  local TEMPDIR=$(mktemp -d)
  local ISO_FILE=$(basename "${ISO_URL}")
  local REG_FILE="livecd-cloud-config.yaml"

  mkdir -p "${TEMPDIR}/iso"
  mkdir -p "${TEMPDIR}/config"

  [ -f "$(pwd)/${ISO_FILE}" ] && abort "$(pwd)/${ISO_FILE} already exists, aborting"

  case ${ISO_URL} in 
    http*)
      wget -O "${TEMPDIR}/iso/${ISO_FILE}" "${ISO_URL}"
      ;;
    *)
      # Assume it is a local path
      [ -f "${ISO_URL}" ] || abort "${ISO_URL} does not exist, aborting"
      cp "${ISO_URL}" "${TEMPDIR}/iso/${ISO_FILE}" 
      ;;
  esac

  cp "${REG_CONFIG_FILE}" "${TEMPDIR}/config/${REG_FILE}"


  docker pull "${BUILD_IMG}"
  docker run --rm -v ${TEMPDIR}:/mnt -v $(pwd):/output ${BUILD_IMG} \
      xorriso -indev "/mnt/iso/${ISO_FILE}" -outdev "/output/${ISO_FILE}" -map "/mnt/config/${REG_FILE}" "/${REG_FILE}" -boot_image any replay

  rm -rf "${TEMPDIR}"

  echo "ISO generated at $(pwd)/${ISO_FILE}"
}

: ${REPO:=Staging}
: ${ARCH:=$(uname -m)}
: ${BUILD_IMG:=registry.opensuse.org/isv/rancher/elemental/${REPO,,}/teal53/15.4/rancher/elemental-builder-image/5.3:latest}
REG_CONFIG_FILE=${1:-}
ISO_URL=${2:-https://download.opensuse.org/repositories/isv:/Rancher:/Elemental:/${REPO}:/Teal53/media/iso/elemental-teal.${ARCH}.iso}

[ "${REPO}" == "Dev" ] || [ "${REPO}" == "Staging" ] || [ "${REPO}" == "Stable" ] || abort "REPO=${REPO} variable has to match Dev|Staging|Stable, aborting"
[ -n "${REG_CONFIG_FILE}" ] || abort "No registration configuration file provided, aborting"
[ -f "${REG_CONFIG_FILE}" ] || abort "${REG_CONFIG_FILE} does not exist, aborting"

echo "Pulling artifacts from isv:Rancher:Elemental:${REPO} OBS project"

iso_repack
