ARG ELEMENTAL_OS_IMAGE

FROM ${ELEMENTAL_OS_IMAGE} as os
FROM ${ELEMENTAL_OS_IMAGE} as builder

COPY manifest.yaml manifest.yaml
COPY --from=os / rootfs

RUN elemental --debug --config-dir . build-iso -o /output -n "elemental-dev" dir:rootfs

FROM busybox:stable

COPY --from=builder /output /elemental-iso
