#!/bin/bash

set -e
export DOCKER_BUILDKIT=0

build() {
  TEMPDIR=$(mktemp -d)
  mkdir "$TEMPDIR"/iso
  # passing a config file? Copy it to the target that will get copied inside the build
  if [[ -n "$CLOUD_CONFIG_FILE" ]]; then
    cp "$CLOUD_CONFIG_FILE" "$TEMPDIR"/iso/config
  fi
  curl https://raw.githubusercontent.com/rancher/elemental/master/Dockerfile.iso -fsSL -o "$TEMPDIR"/Dockerfile
  curl https://raw.githubusercontent.com/rancher/elemental/master/iso/grub.cfg -fsSL -o "$TEMPDIR"/iso/grub.cfg
  # Did we copy the custom cloud config? Then no need to download the default one
  if [[ -z "$CLOUD_CONFIG_FILE" ]]; then
    curl https://raw.githubusercontent.com/rancher/elemental/master/iso/config -fsSL -o "$TEMPDIR"/iso/config
  fi

  pushd "$TEMPDIR" || exit 1
  docker build -f "$TEMPDIR"/Dockerfile -t elemental/iso:latest .
  popd || exit 1

  rm -Rf "$TEMPDIR"
  docker run --rm -v "$PWD":/mnt elemental/iso:latest build-iso -o /mnt --squash-no-compression -n elemental-"$(date "+%FT%TZ")" --overlay-iso overlay dir:rootfs
}

CLOUD_CONFIG_FILE=${1:-}

build


