# Default Elemental OEM configuration file
#
# This file is part of Elemental and will get reset during upgrades.
#
# Before you change this file manually,
# consider copying this file to /usr/local/cloud-config or
# copy the file with a prefix starting by 90, e.g. /oem/91_custom.yaml
name: "SELinux"
stages:
   initramfs:
     - name: "SELinux labels for targeted policy"
       commands:
       - | 
         contexts="/etc/selinux/targeted/contexts/files/file_contexts"
         if grep -qw selinux /sys/kernel/security/lsm && [ -e "${contexts}" ]; then
           # Some extended attributes are lost on copy-up bsc#1210690.
           # Workaround visit children first, then parents
           mkdir -p /run/systemd/relabel-extra.d/
           for path in /etc /srv /oem /home /root /opt /usr/libexec /usr/local; do
             if [ -d "${path}" ]; then
               find ${path} -depth -exec /sbin/setfiles -i -F -v "${contexts}" \{\} +
               echo "${path}" >> /run/systemd/relabel-extra.d/layout.relabel
             fi
           done
         fi
