#!/bin/bash
set -e

. /etc/os-release

IMAGE=$(echo "$IMAGE" | sed 's![/:]!-!g')
for i in rke2 k3s; do
    mkdir -p /etc/rancher/$i/config.yaml.d
    cat > /etc/rancher/$i/config.yaml.d/99-elemental-labels.yaml << EOF
node-label+:
- elemental.cattle.io/image=${IMAGE}
- elemental.cattle.io/tag=${IMAGE_TAG}
- plan.upgrade.cattle.io/os-upgrader=${IMAGE}
EOF
done
