name: "Root autologin"
stages:
  initramfs:
  - if: '[ -f /run/elemental/live_mode ]'
    files:
    - path: /etc/motd
      content: |

        Installation is in progress.
        You can "journalctl -f -u elemental-register-install" to view progress
         
      permissions: 0644
    - path: /etc/systemd/system/serial-getty@ttyS0.service.d/override.conf
      content: |
        [Service]
        ExecStart=
        ExecStart=-/sbin/agetty --autologin root --noclear %I $TERM
      permissions: 0644
    - path: /etc/systemd/system/getty@tty1.service.d/override.conf
      content: |
        [Service]
        ExecStart=
        ExecStart=-/sbin/agetty --autologin root --noclear %I $TERM
      permissions: 0644
