#!/bin/bash
set -x -e

BASE=$(dirname $0)/..
docker buildx build --load -t ros-qemu -f ${BASE}/Dockerfile.kvm ${BASE}

exec docker run -it --rm --net=host -v $(dirname $(pwd)):$(dirname $(pwd)) -w $(pwd) --privileged ros-qemu "$@"