# This workflow calls the master E2E workflow with custom variables
name: K3s-E2E-Latest_RM

# This worflow is scheduled *after* build-ci to be sure that we have
# the lastest version built. The scheduling is also to avoid running
# the worklow on each push on main.
on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  k3s:
    uses: ./.github/workflows/master-e2e.yaml
    secrets:
      credentials: ${{ secrets.GCP_CREDENTIALS }}
      pat_token: ${{ secrets.SELF_HOSTED_RUNNER_PAT_TOKEN }}
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
    with:
      cluster_name: cluster-k3s
      k8s_version_to_provision: v1.24.8+k3s1
      rancher_channel: latest
      rancher_version: devel
      start_condition: ${{ github.event.workflow_run.conclusion }}
      workflow_download: ${{ github.event.workflow_run.workflow_id }}
