name: Lint

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  golang-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          cache-dependency-path: tests/go.sum
          go-version-file: tests/go.mod

      - name: Analysis
        uses: golangci/golangci-lint-action@d6238b002a20823d52840fda27e2d4891c5952dc # v4
        with:
          args: -v
          working-directory: tests

  cypress-lint:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: current
      WORKING_DIR: tests/cypress/latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install npm
        run: |
          cd ${{ env.WORKING_DIR }}
          npm install --save-dev
          npm ls --depth=0

      - name: Analysis
        run: |
          cd ${{ env.WORKING_DIR }}
          npm run lint
