# This workflow is a reusable one called by other workflows
name: (template) CLI/UI template

on:
  workflow_call:
    # Variables to set when calling this reusable workflow
    inputs:
      backup_restore_version:
        required: true
        type: string
      boot_type:
        required: true
        type: string
      ca_type:
        required: true
        type: string
      cert-manager_version:
        required: true
        type: string
      cluster_name:
        required: true
        type: string
      cluster_number:
        required: true
        type: string
      cluster_namespace:
        required: true
        type: string
      cluster_type:
        required: true
        type: string
      cypress_tags:
        required: true
        type: string
      destroy_runner:
        required: true
        type: boolean
      elemental_ui_version:
        required: true
        type: string
      force_downgrade:
        required: true
        type: boolean
      full_backup_restore:
        required: true
        type: boolean
      k8s_downstream_version:
        required: true
        type: string
      k8s_upstream_version:
        required: true
        type: string
      node_number:
        required: true
        type: string
      operator_install_type:
        required: true
        type: string
      operator_repo:
        required: true
        type: string
      operator_upgrade:
        required: true
        type: string
      os_to_test:
        required: true
        type: string
      os_version_install:
        required: true
        type: string
      os_version_target:
        required: true
        type: string
      proxy:
        required: true
        type: string
      public_domain:
        required: true
        type: string
      public_fqdn:
        required: true
        type: string
      qase_project_code:
        required: true
        type: string
      qase_run_id:
        required: true
        type: string
      rancher_git_chart:
        required: true
        type: string
      rancher_upgrade:
        required: true
        type: string
      rancher_version:
        required: true
        type: string
      reset:
        required: true
        type: boolean
      runner_label:
        required: true
        type: string
      selinux:
        required: true
        type: boolean
      sequential:
        required: true
        type: boolean
      snap_type:
        required: true
        type: string
      test_type:
        required: true
        type: string
      ui_account:
        required: true
        type: string
      upgrade_from_version:
        required: true
        type: string
      upgrade_image:
        required: true
        type: string
      upgrade_os_channel:
        required: true
        type: string
      upgrade_type:
        required: true
        type: string

    # Job outputs to export for caller workflow
    outputs:
      steps_status:
        description: Status of the executed test jobs
        value: ${{ join(jobs.*.outputs.steps_status, ' ') }}

    # Secrets to set when calling this reusable workflow
    secrets:
      credentials:
      qase_api_token:

jobs:
  airgap:
    if: ${{ inputs.test_type == 'airgap' }}
    uses: ./.github/workflows/sub_airgap.yaml
    secrets:
      credentials: ${{ secrets.credentials }}
      qase_api_token: ${{ secrets.qase_api_token }}
    with:
      cert-manager_version: ${{ inputs.cert-manager_version }}
      cluster_name: ${{ inputs.cluster_name }}
      cluster_namespace: ${{ inputs.cluster_namespace }}
      k8s_downstream_version: ${{ inputs.k8s_downstream_version }}
      operator_repo: ${{ inputs.operator_repo }}
      os_to_test: ${{ inputs.os_to_test }}
      qase_project_code: ${{ inputs.qase_project_code }}
      qase_run_id: ${{ inputs.qase_run_id }}
      rancher_version: ${{ inputs.rancher_version }}
      runner_label: ${{ inputs.runner_label }}
      snap_type: ${{ inputs.snap_type }}
      test_type: ${{ inputs.test_type }}
      k8s_upstream_version: ${{ inputs.k8s_upstream_version }}

  cli:
    if: ${{ inputs.test_type == 'cli' }}
    uses: ./.github/workflows/sub_cli.yaml
    secrets:
      qase_api_token: ${{ secrets.qase_api_token }}
    with:
      backup_restore_version: ${{ inputs.backup_restore_version }}
      boot_type: ${{ inputs.boot_type }}
      ca_type: ${{ inputs.ca_type }}
      cert-manager_version: ${{ inputs.cert-manager_version }}
      cluster_name: ${{ inputs.cluster_name }}
      cluster_namespace: ${{ inputs.cluster_namespace }}
      cluster_type: ${{ inputs.cluster_type }}
      destroy_runner: ${{ inputs.destroy_runner }}
      force_downgrade: ${{ inputs.force_downgrade }}
      full_backup_restore: ${{ inputs.full_backup_restore }}
      k8s_downstream_version: ${{ inputs.k8s_downstream_version }}
      node_number: ${{ inputs.node_number }}
      operator_install_type: ${{ inputs.operator_install_type }}
      operator_repo: ${{ inputs.operator_repo }}
      operator_upgrade: ${{ inputs.operator_upgrade }}
      os_to_test: ${{ inputs.os_to_test }}
      public_domain: ${{ inputs.public_domain }}
      public_fqdn: ${{ inputs.public_fqdn }}
      qase_project_code: ${{ inputs.qase_project_code }}
      qase_run_id: ${{ inputs.qase_run_id }}
      rancher_upgrade: ${{ inputs.rancher_upgrade }}
      rancher_version: ${{ inputs.rancher_version }}
      reset: ${{ inputs.reset }}
      runner_label: ${{ inputs.runner_label }}
      selinux: ${{ inputs.selinux }}
      sequential: ${{ inputs.sequential }}
      snap_type: ${{ inputs.snap_type }}
      test_type: ${{ inputs.test_type }}
      upgrade_image: ${{ inputs.upgrade_image }}
      upgrade_os_channel: ${{ inputs.upgrade_os_channel }}
      upgrade_type: ${{ inputs.upgrade_type }}
      k8s_upstream_version: ${{ inputs.k8s_upstream_version }}

  multi:
    if: ${{ inputs.test_type == 'multi' }}
    uses: ./.github/workflows/sub_multi.yaml
    secrets:
      qase_api_token: ${{ secrets.qase_api_token }}
    with:
      boot_type: ${{ inputs.boot_type }}
      ca_type: ${{ inputs.ca_type }}
      cert-manager_version: ${{ inputs.cert-manager_version }}
      cluster_name: ${{ inputs.cluster_name }}
      cluster_namespace: ${{ inputs.cluster_namespace }}
      cluster_number: ${{ inputs.cluster_number }}
      cluster_type: ${{ inputs.cluster_type }}
      k8s_downstream_version: ${{ inputs.k8s_downstream_version }}
      operator_install_type: ${{ inputs.operator_install_type }}
      operator_repo: ${{ inputs.operator_repo }}
      os_to_test: ${{ inputs.os_to_test }}
      public_domain: ${{ inputs.public_domain }}
      public_fqdn: ${{ inputs.public_fqdn }}
      qase_project_code: ${{ inputs.qase_project_code }}
      qase_run_id: ${{ inputs.qase_run_id }}
      rancher_version: ${{ inputs.rancher_version }}
      runner_label: ${{ inputs.runner_label }}
      snap_type: ${{ inputs.snap_type }}
      test_type: ${{ inputs.test_type }}
      k8s_upstream_version: ${{ inputs.k8s_upstream_version }}

  ui:
    if: ${{ inputs.test_type == 'ui' }}
    uses: ./.github/workflows/sub_ui.yaml
    secrets:
      qase_api_token: ${{ secrets.qase_api_token }}
    with:
      boot_type: ${{ inputs.boot_type }}
      ca_type: ${{ inputs.ca_type }}
      cert-manager_version: ${{ inputs.cert-manager_version }}
      cluster_name: ${{ inputs.cluster_name }}
      cluster_namespace: ${{ inputs.cluster_namespace }}
      cluster_type: ${{ inputs.cluster_type }}
      cypress_tags: ${{ inputs.cypress_tags }}
      elemental_ui_version: ${{ inputs.elemental_ui_version }}
      k8s_downstream_version: ${{ inputs.k8s_downstream_version }}
      operator_install_type: ${{ inputs.operator_install_type }}
      operator_repo: ${{ inputs.operator_repo }}
      operator_upgrade: ${{ inputs.operator_upgrade }}
      os_to_test: ${{ inputs.os_to_test }}
      os_version_install: ${{ inputs.os_version_install }}
      os_version_target: ${{ inputs.os_version_target }}
      proxy: ${{ inputs.proxy }}
      public_domain: ${{ inputs.public_domain }}
      public_fqdn: ${{ inputs.public_fqdn }}
      qase_project_code: ${{ inputs.qase_project_code }}
      qase_run_id: ${{ inputs.qase_run_id }}
      rancher_git_chart: ${{ inputs.rancher_git_chart }}
      rancher_version: ${{ inputs.rancher_version }}
      runner_label: ${{ inputs.runner_label }}
      ui_account: ${{ inputs.ui_account }}
      upgrade_from_version: ${{ inputs.upgrade_from_version }}
      upgrade_image: ${{ inputs.upgrade_image }}
      upgrade_os_channel: ${{ inputs.upgrade_os_channel }}
      k8s_upstream_version: ${{ inputs.k8s_upstream_version }}
