#!/bin/bash

# Deploy Airgap

set -vx

# Variable(s)
K3S_UPSTREAM_VERSION=$1
OPT_RANCHER=/opt/rancher

# Format upstream version
TMP_UPSTREAM_VERSION=${K3S_UPSTREAM_VERSION/+*}
K8S_UPSTREAM_VERSION=${TMP_UPSTREAM_VERSION/v}

# Install k3s
cd ${OPT_RANCHER}/k3s_${K8S_UPSTREAM_VERSION}
sudo sh -c '
  mkdir -p /var/lib/rancher/k3s/agent/images /etc/rancher/k3s
  cp k3s-airgap-images-amd64.tar.zst /var/lib/rancher/k3s/agent/images/
  chmod +x k3s install.sh
  cp k3s /usr/local/bin/
'

# Add registry configuration
cat <<EOF | sudo tee /etc/rancher/k3s/registries.yaml
mirrors:
  "*":
    endpoint:
      - "http://rancher-manager.test:5000"
configs:
  "*":
    tls:
      insecure_skip_verify: true
EOF

# Add default configuration
cat <<EOF | sudo tee /etc/rancher/k3s/config.yaml
cluster-init: true
disable-default-registry-endpoint: true
EOF

# Pre-load registry image
rsync -avP ${OPT_RANCHER}/registry/registry.tar /var/lib/rancher/k3s/agent/images/

# Install k3s
INSTALL_K3S_SKIP_DOWNLOAD=true INSTALL_K3S_VERSION=${K3S_UPSTREAM_VERSION} ./install.sh
systemctl enable --now k3s

# Wait and add link
sleep 30
mkdir -p ${HOME}/.kube
ln -sf /etc/rancher/k3s/k3s.yaml ${HOME}/.kube/config

# Run local registry
cat <<EOF | kubectl apply -f -
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: registry
  labels:
    app: registry
spec:
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: registry
        imagePullPolicy: Never
        ports:
        - name: registry
          containerPort: 5000
        securityContext:
          capabilities:
            add:
            - NET_BIND_SERVICE
        volumeMounts:
        - name: registry
          mountPath: /var/lib/registry
      volumes:
      - name: registry
        hostPath:
          path: ${OPT_RANCHER}/registry
      hostNetwork: true
EOF

# Wait for registry to be ready
sleep 1m
